services:
  auth-service:
    image: auth-service
    build:
      context: .
    volumes:
      - ./:/opt/www
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    networks:
      - main
    deploy:
      mode: replicated
      replicas: 1

networks:
  main:
    external: true
    name: main_network
